### ISSUE TITLE
Spec

### ISSUE THREAD

**Issue by josephgupkim** [aebasa/jammming#3]
I wasn't able to test the functionality of your project due to a service error:
<img width="417" alt="screen shot 2018-05-29 at 2 09 07 pm" src="https://user-images.githubusercontent.com/17152779/40685761-0277a3a0-634a-11e8-903f-583e209cf330.png">

**Comment by aebasa** [comment]
It wasn't deployed correctly to https. I have made these changes https://aliciabasa.surge.sh/ also have updated to point to https in this repository src/util/Spotify.js
