### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [aebasa/jammming#4]
Overall, a well written Jammming project that seemed promising in its functionality (was not able to test).

If you happen to fix this, please do let me know as I'm fairly confident that you are able to accomplish it!

Grade: Meets expectation.

**Comment by aebasa** [comment]
I have encountered some more errors, am trying to fix and will let you know when its good to check again. Thanks :)

**Comment by aebasa** [comment]
@josephgupkim 
Hi, I think I have it working now. I have updated this repository but have also deployed it here: https://aliciabasa.surge.sh 
Thanks :)
